<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://apache.org" xmlns:xsi="http://w3.org" xsi:schemaLocation="http://apache.org https://apache.org">
	<modelVersion>4.0.0</modelVersion>
	<parent>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-parent</artifactId>
		<version>3.2.5</version>
		<relativePath />
	</parent>

	<groupId>com.example</groupId>
	<artifactId>spring-langchain4j-resourceTracker</artifactId>
	<version>0.0.1-SNAPSHOT</version>
	<name>SpringLangchain4j-Project</name>
	<description>Sample spring Langchain4J project</description>

	<properties>
		<java.L>21</java.L>
		
		<langchain4j.version>1.16.1</langchain4j.version>
	</properties>


	<dependencies>
		<!-- Spring Boot Web starter to create REST endpoints -->
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-web</artifactId>
		</dependency>
		<dependency>
			<groupId>dev.langchain4j</groupId>
			<artifactId>langchain4j</artifactId>
			<version>${langchain4j.version}</version>
		</dependency>
	
		<dependency>
			<groupId>dev.langchain4j</groupId>
			<artifactId>langchain4j-mistral-ai</artifactId>
			<version>${langchain4j.version}</version> <!-- Match the version of your other LangChain4j starters -->

		</dependency>

		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-test</artifactId>
			<scope>test</scope>
		</dependency>
	</dependencies>

	<repositories>
		<repository>
			<id>spring-milestones</id>
			<name>Spring Milestones</name>
			<url>https://repo.spring.io/milestone</url>
			<snapshots>
				<enabled>false</enabled>
			</snapshots>
		</repository>
	</repositories>

	<build>
		<plugins>
			<plugin>
				<groupId>org.springframework.boot</groupId>
				<artifactId>spring-boot-maven-plugin</artifactId>
			</plugin>
		</plugins>
	</build>
</project>