spring.application.name=SpringAIProject
server.port=8082

# Define the free-tier model name
spring.ai.mistralai.chat.options.model=mistral-small

#Enabling virtual thread
spring.threads.virtual.enabled=true

# Points Spring to read the key from your Eclipse environment variables
spring.ai.mistralai.api-key=${MISTRAL_API_KEY}
#spring.main.web-application-type=servlet
